# -*- coding: utf-8 -*-
"""Task 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xZtrCAYWKJOxIcvk8tMKhIsIC5R6xtXk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

df=pd.read_csv("/content/music_data (2)")
df

df.describe

df.shape

sns.boxplot(x="label", y="tempo",data=df)

X = df.drop('label',axis=1)
y = df['label']

sns.boxplot(x='label', y='tempo', data=df, notch=True)
sns.stripplot(x='label', y='tempo', data=df)

x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)
y_pred

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

from google.colab import drive
drive.mount('/content/drive')