# -*- coding: utf-8 -*-
"""Task 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sE6EF-scFDGW534rE-2_CMFi2TfK0vFn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_excel("/content/Task_Data.xlsx")
df

df.info()

df.dropna(subset=['Weight'])

df["DOB"]=df["DOB"].fillna(value="na")

df.Pos.unique()

grouping1=df.groupby('Pos')
grouping1.first()



grouping2=df.groupby('Team')
women=grouping2.get_group('Women')
men=grouping2.get_group('Men')

women

men

#median height of male players
med_ht_men=men['Height'].median()

# mean weight of female players
mean_weight_women=women['Weight'].mean()
mean_weight_women

table = pd.pivot_table(df, values=['Weight', 'Age'], index=['Team', 'Pos'], aggfunc={'Weight': np.mean,'Age': np.mean})
table

grouping3=men.groupby('Country')
canadian_men=grouping3.get_group('Canada')

grouping4=women.groupby('Country')
american_women=grouping4.get_group('USA')

canadian_men

american_women

result = pd.concat([canadian_men,american_women])
result

