# -*- coding: utf-8 -*-
"""Task 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hlUyVworNQ05jvuhXTm3W8BHcv0N-UNe
"""

import pandas as pd

ratings = [['john',5,5,2,1],['mary',4,5,3,2],['bob',4,4,4,3],['lisa',2,2,4,5],['lee',1,2,3,4],['harry',2,1,5,5]]
titles = ['user','Jaws','Star Wars','Exorcist','Omen']
movies = pd.DataFrame(ratings,columns=titles)
movies

from sklearn import cluster 

revised_data = movies.drop('user',axis=1) #dropping user column
solution = cluster.KMeans(n_clusters=2, max_iter=50, random_state=1)
solution.fit(revised_data) 
labels = solution.labels_
pd.DataFrame(labels, index=movies.user, columns=['Cluster_ID'])

centroids = solution.cluster_centers_
pd.DataFrame(centroids,columns=revised_data.columns)

